<template>
  <div class="hello slide-bottom"  style="height:100%;">
    <nav style=" margin: 0 0 0 0;">
      <div class="nav-wrapper">
        <a class="brand-logo" style="cursor: default; margin: 0 0 0 2.5%;"><b>Hacktivpress</b></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li style="margin-right:25px;" @click='Register'><a>Register</a></li>
          <li style="margin-right:25px;" @click='Login'><a>Login</a></li>
          <li style="margin-right:25px;" v-if='checkStorage ==false'><a>Logout</a></li>
        </ul>
      </div>
    </nav>
  </div>
</template>

<script>
import axios from 'axios'
// import Datepicker from 'vuejs-datepicker';

export default {
  created () {
    // this.checkStorage()
  },
  components: {
    // Datepicker
  },
  computed: {
    RegisterForm () {
      // return this.$store.state.registerForm
    },
    getTodo () {
      // return this.$store.state.allTodo
    }
  },
  data () {
    return {
      RegisterData : {
        fullname : '',
        email: '',
        password: '',
        confirm: ''
      },
      newActivity: '',
      todoDescription: '',
      deadline: '',
      date: ''
    }
  },
  methods: {
    Register () {
      this.$store.dispatch('registerform', true)
    },
    Login () {
      this.$store.dispatch('loginform', true)
    },
    checkStorage () {
      if (!localStorage.hasOwnProperty('authorization')) {
        return false
      } else {
        return true
      }
    },
    logout () {
      swal("Are you sure want to logout?", {
        dangerMode: true,
        buttons: true,
      })
      .then((accept) => {
        if (accept) {
          localStorage.clear()
          this.$router.push('/')
        }
      })
    }
  },
  mounted () {
    // $(document).ready(function(){
    //   // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    //   $('.modal-trigger').leanModal()
    // })
  }
}
</script>

<style scoped>
ul {
  list-style-type: none;
  padding: 0;
}
a {
  color: #dfe6e9;
}
nav {
  color: #fff;
  background-color: black;
  width: 100%;
  position: inherit;
  text-align: left;
  position: absolute;
  z-index: 999;
  width: 100%;
}
.slide-bottom {
	-webkit-animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-4 23:57:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-bottom {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
  }
}
@keyframes slide-bottom {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
  }
}

</style>
